global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'videochat-signaling'
    static_configs:
      - targets:
          - 'signaling-1:8080'
          - 'signaling-2:8080'
          - 'signaling-3:8080'
    metrics_path: '/metrics'
